# Generated by Django 3.2.8 on 2021-10-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.IntegerField(max_length=12)),
                ('email', models.EmailField(max_length=150)),
                ('message', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
